services:
  db:
    image: postgres:16
    container_name: commerce_lab_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
      POSTGRES_DB: commerce_lab
    ports:
      - '5432:5432'
    volumes:
      - commerce_lab_db:/var/lib/postgresql/data

volumes:
  commerce_lab_db:
